version: '3.8'

services:
  # --- Service 1 : Le Cerveau (IA Locale) ---
  ollama_service:
    image: ollama/ollama:latest
    volumes:
      - ollama_storage:/root/.ollama
    restart: always

  # --- Service 2 : Le Backend (API Python) ---
  backend_api:  # <--- ICI: On utilise le bon nom de clé pour correspondre aux autres
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/data
    environment:
      # Attention: ici on utilise le nom du service défini plus haut (ollama_service)
      - OLLAMA_BASE_URL=http://ollama_service:11434 
    depends_on:
      - ollama_service

  # --- Service 3 : Frontend (Interface React) ---
  frontend_app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      # 1. On monte le code source pour voir tes modifs en direct
      - ./frontend:/app
      # 2. LA SOLUTION MAGIQUE : On préserve le dossier node_modules du conteneur
      # Cela empêche Windows d'écraser les dépendances Linux et corrige l'erreur "Invalid Hook Call"
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend_api # Maintenant ça correspond bien à la clé du service 2
    environment:
      - NEXT_PUBLIC_API_URL=http://backend_api:8000

volumes:
  ollama_storage:
